services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"

  web:
    build: .
    restart: unless-stopped
    command: [ "gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8080" ]
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./media:/app/media
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - ./media:/app/media
      - certbot_certs:/etc/letsencrypt
      - certbot_certs_data:/var/lib/letsencrypt
      - ./letsencrypt_webroot:/var/lib/letsencrypt/webroot

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot_certs:/etc/letsencrypt
      - certbot_certs_data:/var/lib/letsencrypt
      - ./letsencrypt_webroot:/var/lib/letsencrypt/webroot
    depends_on:
      - nginx

volumes:
  postgres_data:
  static_volume:
  certbot_certs:
  certbot_certs_data: