# Generated by Django 5.2 on 2025-05-21 13:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselColor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "background_color",
                    models.CharField(max_length=55, verbose_name="Background color"),
                ),
                (
                    "percentage_color",
                    models.CharField(max_length=55, verbose_name="Percentage color"),
                ),
                (
                    "button_background_color",
                    models.CharField(
                        max_length=55, verbose_name="Button background color"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel Color",
                "verbose_name_plural": "Carousel Colors",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/files",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        verbose_name="Files",
                    ),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
        migrations.CreateModel(
            name="CarouselDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("url", models.URLField(verbose_name="Url")),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.file",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel Discount",
                "verbose_name_plural": "Carousel Discounts",
            },
        ),
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Text")),
                (
                    "text_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Text"),
                ),
                (
                    "text_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Text"),
                ),
                (
                    "text_en",
                    models.CharField(max_length=255, null=True, verbose_name="Text"),
                ),
                (
                    "percentage",
                    models.PositiveIntegerField(default=0, verbose_name="Percentage"),
                ),
                ("url", models.URLField(verbose_name="Url")),
                (
                    "carousel_color_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="common.carouselcolor",
                        verbose_name="Carousel color",
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.file",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carousel",
                "verbose_name_plural": "Carousels",
            },
        ),
    ]
